addons:
  hosts:
    - node1
dist: trusty
sudo: required
env:
  - MODULES=Client
  - MODULES=Server
  - MODULES=Core
before_cache:
# Never upload Storm artifacts to the build cache, ensuring a clean slate every time
  - rm -rf $HOME/.m2/repository/org/apache/storm

language: java
jdk:
  - oraclejdk8

before_install:
- openssl aes-256-cbc -K $encrypted_dacfc0476f3d_key -iv $encrypted_dacfc0476f3d_iv
  -in id_rsa_travis.enc -out ~/.ssh/id_rsa_travis -d
- chmod 600 ~/.ssh/id_rsa_travis
- echo -e "Host ssh 35.236.128.26\n\tStrictHostKeyChecking no\n\tIdentityFile
  ~/.ssh/id_rsa_travis" >> ~/.ssh/config
addons:
  ssh_known_hosts: 35.236.128.26   
before_install:
  - rvm reload
  - rvm use 2.4.2 --install
  - nvm install 8.9.3
  - nvm use 8.9.3
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - sudo add-apt-repository ppa:deadsnakes/ppa -y
  - sudo apt-get update
  - sudo apt-get install python3.6
  - export MVN_HOME=$HOME/apache-maven-3.6.3
  - if [ ! -d $MVN_HOME/bin ]; then wget https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz -P $HOME; tar xzvf $HOME/apache-maven-3.6.3-bin.tar.gz -C $HOME; fi
  - export PATH=$MVN_HOME/bin:$PATH

install: true
script:
  - /bin/bash ./dev-tools/travis/travis-script.sh $MODULES
  # - mvn clean -Drat.skip=true -DskipTests=true install | egrep -v "(^\[INFO\]|^\[DEBUG\])"
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.rvm"
    - "$NVM_DIR"
    - "$HOME/apache-maven-3.6.3"
after_script:
  - bash .travis/deploy.sh