dist: trusty
sudo: required

before_cache:
# Never upload Storm artifacts to the build cache, ensuring a clean slate every time
  - rm -rf $HOME/.m2/repository/org/apache/storm

language: java
jdk:
  - oraclejdk8
      
# before_install:
#   - rvm reload
#   - rvm use 2.4.2 --install
#   - nvm install 8.9.3
#   - nvm use 8.9.3
#   - sudo apt-get update
#   - sudo apt-get install python3
#   - sudo apt-get install python3-pip
#   - sudo add-apt-repository ppa:deadsnakes/ppa -y
#   - sudo apt-get update
#   - sudo apt-get install python3.6
#   - export MVN_HOME=$HOME/apache-maven-3.6.3
#   - if [ ! -d $MVN_HOME/bin ]; then wget https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz -P $HOME; tar xzvf $HOME/apache-maven-3.6.3-bin.tar.gz -C $HOME; fi
#   - export PATH=$MVN_HOME/bin:$PATH

install: true
script:
  - mvn clean -Drat.skip=true -DskipTests=true install | egrep -v "(^\[INFO\]|^\[DEBUG\])"
cache:
  directories:
    - "$HOME/.m2/repository"